/**
 * Generates API client code based on the endpoint contract.
 * Automatically adapts style (fetch vs axios) based on workspace configuration.
 *
 * Connected to:
 *   - src/extension.ts (commands: generateClient)
 *   - src/views/dashboard-panel.ts (webview panel messages)
 */

import * as fs from 'fs';
import * as path from 'path';
import { RestEndpointDefinition } from '../models/endpoint';

export type ClientStyle = 'fetch' | 'axios';

export interface GeneratedClient {
  code: string;
  style: ClientStyle;
  functionName: string;
  sourceEndpointId: string;
}

export class ClientGenerator {
  public static detectClientStyle(workspaceRoot: string): ClientStyle {
    if (!workspaceRoot || !fs.existsSync(workspaceRoot)) return 'fetch';
    try {
      const pkgPath = path.join(workspaceRoot, 'package.json');
      if (fs.existsSync(pkgPath)) {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
        const deps = { ...pkg.dependencies, ...pkg.devDependencies };
        if (deps['axios']) {
          return 'axios';
        }
      }
    } catch {
      // ignore
    }
    return 'fetch';
  }

  public static generateForEndpoint(
    endpoint: RestEndpointDefinition,
    workspaceRoot: string
  ): GeneratedClient {
    const style = this.detectClientStyle(workspaceRoot);
    const funcName = this.getFunctionName(endpoint.pathPattern, endpoint.method);
    
    // Path params extraction
    const hasPathParams = endpoint.parameters.length > 0;
    const pathArgs = endpoint.parameters.map(p => `${p.name}: string | number`).join(', ');

    // Query params checking
    const nonPagination = endpoint.queryParameters.filter(q => !q.isPagination);
    const hasQueryParams = nonPagination.length > 0;
    const queryArg = hasQueryParams ? 'params?: Record<string, string | number>' : '';

    // Body checking
    const isPayloadMethod = ['POST', 'PUT', 'PATCH'].includes(endpoint.method);
    const bodyArg = isPayloadMethod ? 'data: unknown' : '';

    // Form parameter arguments list
    const argsList = [pathArgs, bodyArg, queryArg].filter(Boolean).join(', ');

    // Path interpolation replacement
    // e.g. /api/users/:id -> `/api/users/${id}`
    let interpolatedPath = endpoint.pathPattern;
    for (const param of endpoint.parameters) {
      interpolatedPath = interpolatedPath.replace(`:${param.name}`, `\${${param.name}}`);
    }
    const pathString = hasPathParams ? `\`${interpolatedPath}\`` : `'${endpoint.pathPattern}'`;

    let code = '';

    if (style === 'axios') {
      code = `import axios from 'axios';

/**
 * ${endpoint.method} ${endpoint.pathPattern}
 * Captured requests: ${endpoint.requestCount}
 * 
 * Generated by TrafficGhost
 */
export async function ${funcName}(${argsList}) {
  const url = ${pathString};
  try {
    const response = await axios({
      method: '${endpoint.method.toLowerCase()}',
      url,
      ${isPayloadMethod ? 'data,' : ''}
      ${hasQueryParams ? 'params,' : ''}
    });
    return response.data;
  } catch (error) {
    console.error('API Error in ${funcName}:', error);
    throw error;
  }
}`;
    } else {
      code = `/**
 * ${endpoint.method} ${endpoint.pathPattern}
 * Captured requests: ${endpoint.requestCount}
 * 
 * Generated by TrafficGhost
 */
export async function ${funcName}(${argsList}) {
  const url = new URL(${pathString}, window.location.origin);
  ${hasQueryParams ? `if (params) {
    Object.entries(params).forEach(([k, v]) => url.searchParams.append(k, String(v)));
  }` : ''}

  const response = await fetch(url.toString(), {
    method: '${endpoint.method}',
    headers: {
      'Content-Type': 'application/json',
    },
    ${isPayloadMethod ? 'body: JSON.stringify(data)' : ''}
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${endpoint.pathPattern}: \${response.statusText}\`);
  }

  return response.json();
}`;
    }

    return {
      code,
      style,
      functionName: funcName,
      sourceEndpointId: endpoint.id
    };
  }

  private static getFunctionName(pathPattern: string, method: string): string {
    const segments = pathPattern
      .replace(/:[a-zA-Z0-9]+/g, '')
      .split('/')
      .filter(Boolean)
      .filter(s => s !== 'api' && s !== 'v1' && s !== 'v2')
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');

    const base = segments || 'Resource';
    
    // Singularize base for detail methods
    const hasParams = pathPattern.includes('/:');
    let item = base;
    if (base.endsWith('s') && hasParams) {
      item = base.substring(0, base.length - 1);
    }

    switch (method.toUpperCase()) {
      case 'GET':
        return hasParams ? `get${item}` : `list${base}`;
      case 'POST':
        return `create${item}`;
      case 'PUT':
      case 'PATCH':
        return `update${item}`;
      case 'DELETE':
        return `delete${item}`;
      default:
        return `fetch${base}`;
    }
  }
}
