/**
 * Generates test skeletons based on captured endpoint details and observed HTTP status codes.
 *
 * Connected to:
 *   - src/extension.ts (commands: generateTest)
 */

import * as fs from 'fs';
import * as path from 'path';
import { RestEndpointDefinition } from '../models/endpoint';

export type TestFramework = 'jest' | 'vitest' | 'mocha' | 'node-test';

export interface GeneratedTest {
  code: string;
  framework: TestFramework;
  testCount: number;
  sourceEndpointId: string;
}

export class TestGenerator {
  public static detectFramework(workspaceRoot: string): TestFramework {
    if (!workspaceRoot || !fs.existsSync(workspaceRoot)) return 'jest';
    try {
      const pkgPath = path.join(workspaceRoot, 'package.json');
      if (fs.existsSync(pkgPath)) {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
        const deps = { ...pkg.dependencies, ...pkg.devDependencies };
        if (deps['vitest']) return 'vitest';
        if (deps['mocha']) return 'mocha';
      }
    } catch {
      // ignore
    }
    return 'jest';
  }

  public static generateForEndpoint(
    endpoint: RestEndpointDefinition,
    workspaceRoot: string
  ): GeneratedTest {
    const framework = this.detectFramework(workspaceRoot);
    const method = endpoint.method;
    const pathPattern = endpoint.pathPattern;
    
    // Extract unique status codes observed in captured traffic
    const statusCodes = [...new Set(endpoint.responses.map(r => r.statusCode))];
    if (!statusCodes.includes(200) && !statusCodes.includes(201) && !statusCodes.includes(204)) {
      statusCodes.push(200); // make sure we have a success case
    }

    const testBlocks: string[] = [];
    
    for (const code of statusCodes) {
      const isSuccess = code >= 200 && code < 300;
      const testName = isSuccess 
        ? `should return ${code} on successful request` 
        : `should handle ${code} error responses gracefully`;

      if (framework === 'vitest' || framework === 'jest') {
        testBlocks.push(`  it('${testName}', async () => {
    // Setup request intercept or mock server port configuration
    const response = await fetch('http://localhost:4000${pathPattern.replace(/:[a-zA-Z0-9]+/g, '1')}', {
      method: '${method}',
      headers: { 'Content-Type': 'application/json' },
      ${['POST', 'PUT', 'PATCH'].includes(method) ? "body: JSON.stringify({ /* payload */ })" : ''}
    });
    
    expect(response.status).toBe(${code});
    const data = await response.json();
    expect(data).toBeDefined();
    ${isSuccess ? '// Validate returned response structure' : '// Validate error handling properties'}
  });`);
      } else {
        // Mocha / Node-test callback style or standard test block
        testBlocks.push(`  it('${testName}', async () => {
    const response = await fetch('http://localhost:4000${pathPattern.replace(/:[a-zA-Z0-9]+/g, '1')}', {
      method: '${method}',
      headers: { 'Content-Type': 'application/json' }
    });
    assert.strictEqual(response.status, ${code});
  });`);
      }
    }

    let code = '';
    if (framework === 'vitest') {
      code = `import { describe, it, expect } from 'vitest';

// Generated by TrafficGhost from captured traffic
describe('${method} ${pathPattern}', () => {
${testBlocks.join('\n\n')}
});`;
    } else if (framework === 'jest') {
      code = `// Generated by TrafficGhost from captured traffic
describe('${method} ${pathPattern}', () => {
${testBlocks.join('\n\n')}
});`;
    } else {
      code = `const assert = require('assert');

describe('${method} ${pathPattern}', () => {
${testBlocks.join('\n\n')}
});`;
    }

    return {
      code,
      framework,
      testCount: statusCodes.length,
      sourceEndpointId: endpoint.id
    };
  }

  public static generateResilienceTest(
    endpoint: RestEndpointDefinition,
    workspaceRoot: string
  ): GeneratedTest {
    const framework = this.detectFramework(workspaceRoot);
    const method = endpoint.method;
    const pathPattern = endpoint.pathPattern;
    const testBlocks: string[] = [];

    const resilienceCases = [
      { code: 200, name: 'should load data successfully on HTTP 200' },
      { code: 401, name: 'should handle HTTP 401 Unauthorized status by clearing session or prompting re-auth' },
      { code: 404, name: 'should display resource not found notification on HTTP 404' },
      { code: 429, name: 'should trigger retry countdown or queue requests on HTTP 429 Too Many Requests' },
      { code: 500, name: 'should handle HTTP 500 Internal Server Error gracefully without crashing' },
      { code: 'timeout', name: 'should trigger fallback timeout and cancel slow requests > 3000ms' }
    ];

    for (const testCase of resilienceCases) {
      if (framework === 'vitest' || framework === 'jest') {
        if (testCase.code === 'timeout') {
          testBlocks.push(`  it('${testCase.name}', async () => {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000);
    
    try {
      await fetch('http://localhost:4000${pathPattern.replace(/:[a-zA-Z0-9]+/g, '1')}', {
        method: '${method}',
        signal: controller.signal
      });
      clearTimeout(timeoutId);
    } catch (err: any) {
      expect(err.name).toBe('AbortError');
    }
  });`);
        } else {
          testBlocks.push(`  it('${testCase.name}', async () => {
    const response = await fetch('http://localhost:4000${pathPattern.replace(/:[a-zA-Z0-9]+/g, '1')}', {
      method: '${method}',
      headers: { 
        'Content-Type': 'application/json',
        'x-simulated-status': '${testCase.code}'
      }
    });
    
    expect(response.status).toBe(${testCase.code});
    if (${testCase.code} === 429) {
      const retryAfter = response.headers.get('Retry-After');
      expect(retryAfter).toBeDefined();
    }
  });`);
        }
      } else {
        // Mocha / Node
        testBlocks.push(`  it('${testCase.name}', async () => {
    // Basic assertions
    const response = await fetch('http://localhost:4000${pathPattern.replace(/:[a-zA-Z0-9]+/g, '1')}', {
      method: '${method}'
    });
    assert.ok(response);
  });`);
      }
    }

    let code = '';
    if (framework === 'vitest') {
      code = `import { describe, it, expect } from 'vitest';

// Generated by TrafficGhost Resilience Test Generator
describe('${method} ${pathPattern} - Failure Injection Resilience Suite', () => {
${testBlocks.join('\n\n')}
});`;
    } else if (framework === 'jest') {
      code = `// Generated by TrafficGhost Resilience Test Generator
describe('${method} ${pathPattern} - Failure Injection Resilience Suite', () => {
${testBlocks.join('\n\n')}
});`;
    } else {
      code = `const assert = require('assert');

// Generated by TrafficGhost Resilience Test Generator
describe('${method} ${pathPattern} - Failure Injection Resilience Suite', () => {
${testBlocks.join('\n\n')}
});`;
    }

    return {
      code,
      framework,
      testCount: resilienceCases.length,
      sourceEndpointId: endpoint.id
    };
  }
}
