/**
 * Generates TypeScript interfaces from actual response payloads (and request bodies if present).
 *
 * Connected to:
 *   - src/extension.ts (commands: generateTypes)
 *   - src/views/dashboard-panel.ts (webview interface requests)
 */

import { RestEndpointDefinition, GraphQLEndpointDefinition } from '../models/endpoint';

export interface GeneratedTypes {
  declarations: string;
  interfaces: string[];
  sourceEndpointId: string;
  sourceMethod: string;
  sourcePath: string;
}

export class TypeGenerator {
  public static generateFromEndpoint(
    endpoint: RestEndpointDefinition | GraphQLEndpointDefinition
  ): GeneratedTypes {
    const isRest = 'method' in endpoint;
    const method = isRest ? (endpoint as RestEndpointDefinition).method : 'POST';
    const pathPattern = isRest ? (endpoint as RestEndpointDefinition).pathPattern : (endpoint as GraphQLEndpointDefinition).path;
    const nameInfo = this.formatName(pathPattern, method, isRest ? undefined : (endpoint as GraphQLEndpointDefinition).operationName);
    
    const body = endpoint.defaultResponse?.body;
    const declarations: string[] = [];
    const generatedNames: string[] = [];

    declarations.push(`// Generated by TrafficGhost from captured traffic`);
    declarations.push(`// Method: ${method} | Path: ${pathPattern}\n`);

    if (body !== undefined && body !== null) {
      if (Array.isArray(body)) {
        let itemName = nameInfo.response;
        if (itemName.endsWith('Response')) {
          itemName = itemName.substring(0, itemName.length - 8);
        }
        if (itemName.endsWith('s')) {
          itemName = itemName.substring(0, itemName.length - 1);
        }
        if (body.length > 0) {
          const rootType = this.generateForValue(body[0], itemName, declarations, generatedNames);
          declarations.push(`export interface ${nameInfo.response} extends Array<${rootType}> {}`);
          generatedNames.push(nameInfo.response);
        } else {
          declarations.push(`export interface ${nameInfo.response} extends Array<unknown> {}`);
          generatedNames.push(nameInfo.response);
        }
      } else {
        const rootType = this.generateForValue(body, nameInfo.response, declarations, generatedNames);
        if (typeof body !== 'object') {
          declarations.push(`export type ${nameInfo.response} = ${rootType};`);
          generatedNames.push(nameInfo.response);
        }
      }
    } else {
      declarations.push(`export type ${nameInfo.response} = unknown;`);
      generatedNames.push(nameInfo.response);
    }

    return {
      declarations: declarations.join('\n'),
      interfaces: generatedNames,
      sourceEndpointId: endpoint.id,
      sourceMethod: method,
      sourcePath: pathPattern
    };
  }

  private static formatName(pathPattern: string, method: string, opName?: string): { response: string; item: string } {
    if (opName) {
      // GraphQL
      const cleanOp = opName.charAt(0).toUpperCase() + opName.slice(1);
      return {
        response: `${cleanOp}Response`,
        item: `${cleanOp}Item`
      };
    }

    // REST e.g. /api/v1/users/:id -> User
    const cleanPath = pathPattern
      .replace(/:[a-zA-Z0-9]+/g, '')
      .split('/')
      .filter(Boolean)
      .filter(s => s !== 'api' && s !== 'v1' && s !== 'v2')
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');

    const baseName = cleanPath || 'Resource';
    
    // Singularize if ends with 's' for item name
    let item = baseName;
    if (baseName.endsWith('s')) {
      item = baseName.substring(0, baseName.length - 1);
    }

    return {
      response: `${baseName}Response`,
      item: `${item}`
    };
  }

  private static generateForValue(
    value: unknown,
    name: string,
    declarations: string[],
    generatedNames: string[]
  ): string {
    if (value === null) return 'null';
    if (value === undefined) return 'undefined';

    if (Array.isArray(value)) {
      if (value.length > 0) {
        // Singular interface name
        const singularName = name.endsWith('Response') ? name.replace('Response', '') : `${name}Item`;
        const elementType = this.generateForValue(value[0], singularName, declarations, generatedNames);
        return `${elementType}[]`;
      }
      return 'unknown[]';
    }

    if (typeof value === 'object') {
      const obj = value as Record<string, unknown>;
      const lines: string[] = [];
      lines.push(`export interface ${name} {`);

      for (const [key, val] of Object.entries(obj)) {
        const cleanKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
        let valType = 'unknown';

        if (val === null) {
          valType = 'null';
        } else if (Array.isArray(val)) {
          if (val.length > 0 && typeof val[0] === 'object') {
            const nestedName = `${name}_${key.charAt(0).toUpperCase() + key.slice(1)}`;
            const elType = this.generateForValue(val[0], nestedName, declarations, generatedNames);
            valType = `${elType}[]`;
          } else {
            valType = 'unknown[]';
          }
        } else if (typeof val === 'object') {
          const nestedName = `${name}_${key.charAt(0).toUpperCase() + key.slice(1)}`;
          valType = this.generateForValue(val, nestedName, declarations, generatedNames);
        } else {
          valType = typeof val;
        }

        lines.push(`  ${cleanKey}: ${valType};`);
      }

      lines.push(`}`);
      declarations.push(lines.join('\n'));
      generatedNames.push(name);
      return name;
    }

    return typeof value;
  }
}
